Repository ut-issl/c2a-tlm-cmd-code-generator, pull requests merged in 2022-02, with the labels that each got.

#18 無効TLMのチェック方法を修正
  my_mod/load_db.py
Labels: priority::medium

#17 新しいC2A間通信とSpacePacketの対応
  README.md
  my_mod/tlm_buffer.py
  my_mod/tlm_def.py
  settings.json
Labels: priority::high, tools

#19 local vars で カンマがExcelの仕様で@@に置換されてしまう問題を修正
  my_mod/load_db.py
Labels: bug, priority::medium
